<a href="https://colab.research.google.com/github/krishnavarathan/python-data-analysis/blob/main/A_Loan_Data_Preprocessing_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing the Packages

In [862]:
import numpy as np

In [863]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

In [864]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Importing the Data

In [865]:
source=np.genfromtxt("/content/drive/MyDrive/Loan_Data/loan-data.csv",
              delimiter=';',
              autostrip= True,
              skip_header=1,
              encoding='latin1' # To avoid Error- UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 341: invalid start byte
              )
source

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [866]:
np.isnan(source).sum() # Method chaining

np.int64(88005)

In [867]:
temp_max=int(np.nanmax(source)+1)
temp_mean=np.nanmean(source, axis=0)


/tmp/ipython-input-109970605.py:2: RuntimeWarning: Mean of empty slice
  temp_mean=np.nanmean(source, axis=0)


In [868]:
print(temp_max)
print(temp_mean)

68616520
[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92
         nan         nan         nan         nan         nan     3143.85]


In [869]:
columns = ['Min', 'Mean', 'Max']  # Change names as needed
temp_statics= np.array([np.nanmin(source, axis=0),
                       temp_mean,
                       np.nanmax(source, axis=0)],
                       )


/tmp/ipython-input-2084798063.py:2: RuntimeWarning: All-NaN slice encountered
  temp_statics= np.array([np.nanmin(source, axis=0),
/tmp/ipython-input-2084798063.py:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(source, axis=0)],


In [870]:
temp_statics

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [871]:
columns_strings = np.argwhere(np.isnan(temp_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [872]:
columns_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

### Re-importing the Dataset

In [873]:
string_values=np.genfromtxt("/content/drive/MyDrive/Loan_Data/loan-data.csv",
              delimiter=';',
              autostrip= True,
              skip_header=1,
              dtype=str,
              usecols=columns_strings,
              encoding='latin1' # To avoid Error- UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 341: invalid start byte
              )
string_values

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [874]:
# To remove the specfic '-15', char for the entire column
# np.chararray.strip(string_values[:,0], '-15')

In [875]:
numeric_values=np.genfromtxt("/content/drive/MyDrive/Loan_Data/loan-data.csv",
              delimiter=';',
              autostrip= True,
              skip_header=1,
              usecols=columns_numeric,
              filling_values=temp_max,
              encoding='latin1' # To avoid Error- UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 341: invalid start byte
              )
numeric_values

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The Names of the Columns

In [876]:
source.shape[0] # 10,000
full_headers=np.genfromtxt('/content/drive/MyDrive/Loan_Data/loan-data.csv',
                           delimiter=';',
                           autostrip=True,
                           dtype=str,
                           skip_footer=source.shape[0],
                           encoding='latin1' # To avoid UnicodeDecodeError
                           )
full_headers

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [877]:
string_headers, numeric_headers = full_headers[columns_strings], full_headers[columns_numeric]

# header_strings, header_numeric = header_full[columns_strings], header_full[columns_numeric]

In [878]:
string_headers

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [879]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints:

In [880]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [881]:
val=checkpoint("string-value-checkpoints", string_headers, string_values)

In [882]:
val['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [883]:
np.equal(val['data'], string_values)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

## Manipulating String Columns

In [884]:
string_headers

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [885]:
string_headers[0]='issue_date'

In [886]:
string_values

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Issue Date

In [887]:
np.unique(string_values[:,0])
# np.unique(string_values[:,1])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [888]:
string_values[:,0] = np.chararray.strip(string_values[:,0], '-15')

/tmp/ipython-input-361827165.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  string_values[:,0] = np.chararray.strip(string_values[:,0], '-15')


In [889]:
np.unique(string_values[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [890]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [891]:
for i in range(13):
        print(string_values[:,0], end=" ")
        string_values[:,0] = np.where(string_values[:,0] == months[i],
                                          str(i),
                                          string_values[:,0])

['May' '' 'Sep' ... 'Jun' 'Apr' 'Dec'] ['May' '0' 'Sep' ... 'Jun' 'Apr' 'Dec'] ['May' '0' 'Sep' ... 'Jun' 'Apr' 'Dec'] ['May' '0' 'Sep' ... 'Jun' 'Apr' 'Dec'] ['May' '0' 'Sep' ... 'Jun' 'Apr' 'Dec'] ['May' '0' 'Sep' ... 'Jun' '4' 'Dec'] ['5' '0' 'Sep' ... 'Jun' '4' 'Dec'] ['5' '0' 'Sep' ... '6' '4' 'Dec'] ['5' '0' 'Sep' ... '6' '4' 'Dec'] ['5' '0' 'Sep' ... '6' '4' 'Dec'] ['5' '0' '9' ... '6' '4' 'Dec'] ['5' '0' '9' ... '6' '4' 'Dec'] ['5' '0' '9' ... '6' '4' 'Dec'] 

In [892]:
np.unique(string_values[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [893]:
string_headers

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [894]:
np.unique(string_values[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [895]:
np.unique(string_values[:,1]).size

9

In [896]:
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [897]:
string_values[:,1] = np.where(np.isin(string_values[:,1], status_bad),0,1)

In [898]:
np.unique(string_values[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [899]:
string_headers

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [900]:
np.unique(string_values[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [901]:
string_values[:,2] = np.chararray.strip(string_values[:,2], " months")
string_values[:,2]

/tmp/ipython-input-2045469625.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  string_values[:,2] = np.chararray.strip(string_values[:,2], " months")


array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [902]:
string_values[:,2] = np.where(string_values[:,2] == '',
                                  '60',
                                  string_values[:,2])
string_values[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [903]:
np.unique(string_values[:,2])

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [904]:
string_headers

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [905]:
np.unique(string_values[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [906]:
np.unique(string_values[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Filling Sub Grade

In [907]:
for i in np.unique(string_values[:,3])[1:]:
    string_values[:,4] = np.where((string_values[:,4] == '') & (string_values[:,3] == i),
                                      i + '5',
                                      string_values[:,4])

In [908]:
np.unique(string_values[:,4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [909]:
string_values[:,4] = np.where(string_values[:,4] == '',
                                  'H1',
                                  string_values[:,4])

In [910]:
np.unique(string_values[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### Removing Grade

In [911]:
string_values = np.delete(string_values, 3, axis = 1)

In [912]:
string_values[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [913]:
string_headers = np.delete(string_headers, 3)

In [914]:
string_headers[3]

np.str_('sub_grade')

#### Converting Sub Grade

In [915]:
np.unique(string_values[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [916]:
keys = list(map(str, np.unique(string_values[:,3])))
values = list(range(1, np.unique(string_values[:,3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys, values))

In [917]:
print(dict_sub_grade)

{'A1': 1, 'A2': 2, 'A3': 3, 'A4': 4, 'A5': 5, 'B1': 6, 'B2': 7, 'B3': 8, 'B4': 9, 'B5': 10, 'C1': 11, 'C2': 12, 'C3': 13, 'C4': 14, 'C5': 15, 'D1': 16, 'D2': 17, 'D3': 18, 'D4': 19, 'D5': 20, 'E1': 21, 'E2': 22, 'E3': 23, 'E4': 24, 'E5': 25, 'F1': 26, 'F2': 27, 'F3': 28, 'F4': 29, 'F5': 30, 'G1': 31, 'G2': 32, 'G3': 33, 'G4': 34, 'G5': 35, 'H1': 36}


In [918]:
col = string_values[:,3]

mapped_column = np.array([str(dict_sub_grade[x]) if x in dict_sub_grade else '0' for x in col])
string_values[:,3] = mapped_column

print(mapped_column)

['13' '5' '10' ... '5' '17' '4']


In [919]:
np.unique(string_values[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [920]:
string_headers

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [921]:
np.unique(string_values[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [922]:
string_values[:,4] = np.where((string_values[:,4] == '') | (string_values[:,4] == 'Not Verified'), 0, 1)

In [923]:
np.unique(string_values[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [924]:
string_headers

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [925]:
string_values[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [926]:
url=np.chararray.strip(string_values[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')
url

/tmp/ipython-input-1727054702.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  url=np.chararray.strip(string_values[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')


array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [927]:
string_values[:,5] = np.chararray.strip(string_values[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

/tmp/ipython-input-3490553408.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  string_values[:,5] = np.chararray.strip(string_values[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")


In [928]:
full_headers

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [929]:
numeric_values[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [930]:
string_values[:,5].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [931]:
# Both url and id columns having same id's
np.array_equal(string_values[:,5].astype(dtype=np.int32), numeric_values[:,0].astype(dtype = np.int32))

True

In [932]:
# Deleting the url column
string_values = np.delete(string_values, 5, axis = 1)
string_headers = np.delete(string_headers, 5)

In [933]:
string_values[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [934]:
string_headers

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [935]:
print(numeric_values[:,0])
print(numeric_headers)

[48010226. 57693261. 59432726. ... 50415990. 46154151. 66055249.]
['id' 'loan_amnt' 'funded_amnt' 'int_rate' 'installment' 'total_pymnt']


### State Address

In [936]:
string_headers

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [937]:
string_values[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [938]:
states_names, states_count = np.unique(string_values[:,5], return_counts = True)
print(states_count[20])

10


In [939]:
states_names, states_count = np.unique(string_values[:,5], return_counts = True)
states_count_sorted = np.argsort(-states_count)
print(states_count_sorted)
print(states_names[states_count_sorted], states_count[states_count_sorted])

[ 5 33 42 10  0 13 30 11 37 34 21 26 44 19  4 46 18  6 23 22 14 47 41  7 32  2 17 36 39 16 15 35 43
  3 24 29 31 48 12 38 25  8  9 49  1 28 40 45 27 20]
['CA' 'NY' 'TX' 'FL' '' 'IL' 'NJ' 'GA' 'PA' 'OH' 'MI' 'NC' 'VA' 'MD' 'AZ' 'WA' 'MA' 'CO' 'MO' 'MN'
 'IN' 'WI' 'TN' 'CT' 'NV' 'AL' 'LA' 'OR' 'SC' 'KY' 'KS' 'OK' 'UT' 'AR' 'MS' 'NH' 'NM' 'WV' 'HI'
 'RI' 'MT' 'DC' 'DE' 'WY' 'AK' 'NE' 'SD' 'VT' 'ND' 'ME'] [1336  777  758  690  500  389  341  321  320  312  267  261  242  222  220  216  210  201  160
  156  152  148  143  143  130  119  116  108  107   84   84   83   74   74   61   58   57   49
   44   40   28   27   27   27   26   25   24   17   16   10]


In [940]:
string_values[:,5] = np.where(string_values[:,5] == '',
                                  '0',
                                  string_values[:,5])

In [941]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [942]:
string_values[:,5] = np.where(np.isin(string_values[:,5], states_west), '1', string_values[:,5])
string_values[:,5] = np.where(np.isin(string_values[:,5], states_south), '2', string_values[:,5])
string_values[:,5] = np.where(np.isin(string_values[:,5], states_midwest), '3', string_values[:,5])
string_values[:,5] = np.where(np.isin(string_values[:,5], states_east), '4', string_values[:,5])

In [943]:
np.unique(string_values[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [944]:
string_values

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [945]:
string_values = string_values.astype(np.int32)

In [946]:
string_values

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], dtype=int32)

### Checkpoint 1: Strings

In [947]:
checkpoint_str = checkpoint("chehcking", string_headers, string_values)

In [948]:
checkpoint_str['header']

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [949]:
checkpoint_str['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], dtype=int32)

In [950]:
np.array_equal(string_values, checkpoint_str['data'])

True

## Manipulating Numeric Columns

In [951]:
numeric_values

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [952]:
np.isnan(numeric_values).sum()

np.int64(0)

### Substitute "Filler" Values

In [953]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [954]:
temp_max

68616520

In [955]:
np.isin(numeric_values[:,0], temp_max)

array([False, False, False, ..., False, False, False])

In [956]:
np.isin(numeric_values[:,0], temp_max).sum()

np.int64(0)

In [957]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### Temporary Stats

In [958]:
temp_statics[:, columns_numeric] # 1st row min, 2nd row mean, 3rd row max

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [959]:
numeric_values[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [960]:
numeric_values[:,2] = np.where(numeric_values[:,2] == temp_max,
                                  temp_mean[4],
                                  numeric_values[:,2])
numeric_values[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [961]:
temp_statics[0, columns_numeric[3]]

np.float64(6.0)

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [962]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [963]:
for i in [1,3,4,5]:
    numeric_values[:,i] = np.where(numeric_values[:,i] == temp_max,
                                      temp_statics[1, columns_numeric[i]],
                                      numeric_values[:,i])

In [964]:
numeric_values

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       16.62,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       16.62,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       16.62,      440.92,     2185.64],
       [46154151.  ,    15273.46,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       16.62,      309.97,      301.9 ]])

### Currency Change

#### The Exchange Rate

In [965]:
esd_usd= np.genfromtxt('/content/drive/MyDrive/Loan_Data/EUR-USD.csv',
                       delimiter=',',
                       autostrip=True,
                       skip_header=1,
                       usecols=3 # Loaded inly the 3th column whisch close
                       )
esd_usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [966]:
string_values[:,0]

array([ 5,  0,  9, ...,  6,  4, 12], dtype=int32)

In [967]:
exchange_rate = string_values[:,0]

for i in range(1,13):
  exchange_rate = np.where(exchange_rate == i,
                             esd_usd[i-1],
                             exchange_rate)

exchange_rate = np.where(exchange_rate == 0,
                         np.mean(esd_usd),
                         exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [968]:
exchange_rate.shape

(10000,)

In [969]:
numeric_values.shape

(10000, 6)

In [970]:
exchange_rate = np.reshape(exchange_rate, (10000,1))
exchange_rate.shape

(10000, 1)

In [971]:
numeric_values = np.hstack((numeric_values, exchange_rate))
numeric_values

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,      440.92,     2185.64,        1.12],
       [46154151.  ,    15273.46,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [972]:
# Adding a column name
numeric_headers = np.concatenate((numeric_headers, np.array(['exchange_rate'])))
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### From USD to EUR

In [973]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [974]:
columns_dollar = np.array([1,2,4,5])

In [975]:
numeric_values[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [976]:
for i in columns_dollar:
    numeric_values = np.hstack((numeric_values, np.reshape(numeric_values[:,i] / numeric_values[:,6], (10000,1))))


In [977]:
numeric_values.shape

(10000, 11)

In [978]:
numeric_values

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,      392.87,     1947.47],
       [46154151.  ,    15273.46,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

#### Expanding the header

In [979]:
print(columns_dollar)
header_additional = np.array([column_name + '_EUR' for column_name in numeric_headers[columns_dollar]])

[1 2 4 5]


In [980]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [981]:
numeric_headers = np.concatenate((numeric_headers, header_additional))

In [982]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [983]:
numeric_headers[columns_dollar] = np.array([column_name + '_USD' for column_name in numeric_headers[columns_dollar]])


In [984]:
numeric_headers

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [985]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [986]:
numeric_headers = numeric_headers[columns_index_order]

In [987]:
numeric_values

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,      392.87,     1947.47],
       [46154151.  ,    15273.46,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [988]:
numeric_values = numeric_values[:,columns_index_order]

In [989]:
numeric_values

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    15273.46,    13742.15, ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [990]:
numeric_values.shape

(10000, 11)

### Interest Rate

In [991]:
numeric_headers

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [992]:
numeric_values[:,5]

array([13.33, 16.62, 16.62, ..., 16.62, 16.55, 16.62])

In [993]:
numeric_values[:,5] = numeric_values[:,5]/100

In [994]:
numeric_values[:,5]

array([0.13, 0.17, 0.17, ..., 0.17, 0.17, 0.17])

### Checkpoint 2: Numeric

In [995]:
checkpoint_numeric = checkpoint("Checkpoint-Numeric", numeric_headers, numeric_values)

In [996]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    15273.46,    13742.15, ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the "Complete" Dataset

In [997]:
checkpoint_str['data'].shape

(10000, 6)

In [998]:
checkpoint_numeric['data'].shape

(10000, 11)

In [999]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_str['data']))

In [1000]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    15273.46,    13742.15, ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [1001]:
# checking Null-Values
np.isnan(loan_data).sum()

np.int64(0)

In [1002]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_str['header']))
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

## Sorting the New Dataset

In [1003]:
index=np.argsort(loan_data[:,0])
loan_data = loan_data[index]

In [1004]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [1005]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

## Storing the New Dataset

In [1006]:
loan_data = np.vstack((header_full, loan_data))

In [1007]:
np.savetxt('loan-data-preprocessed.csv',loan_data,
           delimiter=',',
           fmt="%s"
           )

# np.savetxt("loan-data-preprocessed.csv",
#            loan_data,
#            fmt = '%s',
#            delimiter = ',')