<a href="https://colab.research.google.com/github/krishnavarathan/python-data-analysis/blob/main/Importing_Text_Data_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing Data with NumPy

### 1. Run the following cells:

In [137]:
import numpy as np
import pandas as pd

In [138]:
np.set_printoptions(suppress = True, linewidth = 150)

### 2. Use loadtxt() to import the same file and display its contents.
   <b> Hint:</b> By default np.loadtxt() asusmes all the values will be numeric, so it crashes when it encounters text data. We can bypass this by specifying the datatype to NumPy strings when importing.

In [139]:
lt = np.loadtxt("/content/drive/MyDrive/Lending-Company-Total-Price.csv", delimiter=',', dtype=str) # If we remove/change the data type of the file it's throw's the error.
print(lt)

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600']
 ...
 ['413' 'id_413' 'Product B' ... 'Location 135' 'Region 1' '16600']
 ['414' 'id_414' 'Product C' ... 'Location 200' 'Region 6' '15600']
 ['415' 'id_415' 'Product A' ... 'Location 8' 'Region 2' '22250']]


**Error Handling and Pre-processing**
This section attempts to load the dataset using numpy.loadtxt. Due to the strict numeric requirements of this method, a try-except block is implemented to catch and describe potential ValueError exceptions (typically caused by headers or non-numeric strings).

In [140]:
try:
  lt = np.loadtxt("/content/drive/MyDrive/Lending-Company-Total-Price.csv", delimiter=',') # Handling the error'r using try and expect.
except ValueError as e:
  print(f"Lending-Company-Total-Price.csv Cause: {e}")
  print("Recommendation: Adjust the 'dtype' argument in np.loadtxt() to accommodate non-numeric values.")
#print(lt)

Lending-Company-Total-Price.csv Cause: could not convert string 'LoanID' to float64 at row 0, column 1.
Recommendation: Adjust the 'dtype' argument in np.loadtxt() to accommodate non-numeric values.


In [141]:
print(type(lt))

<class 'numpy.ndarray'>


In [142]:
lt.shape

(416, 7)

### 3. Use np.genfromtxt() to import the "Lending-Company-Total-Price.csv" file and display its contents.
    You can open the file in a text editor like Notepad++ to check its delimiter.

In [143]:
gen = np.genfromtxt("/content/drive/MyDrive/Lending-Company-Total-Price.csv", delimiter=",") # genfromtext handles the Null value data as well, loadtxt can't

In [144]:
print(gen)
print(type(gen))

[[   nan    nan    nan ...    nan    nan    nan]
 [    1.    nan    nan ...    nan    nan 16600.]
 [    2.    nan    nan ...    nan    nan 16600.]
 ...
 [  413.    nan    nan ...    nan    nan 16600.]
 [  414.    nan    nan ...    nan    nan 15600.]
 [  415.    nan    nan ...    nan    nan 22250.]]
<class 'numpy.ndarray'>


### 4. Using the arguments of the np.genfromtxt() function, do the following data cleaning:
    A) Set the data type to strings.
    B) Skip the first row of the dataset.
    C) Skip the last 15 rows of the dataset.
    D) Only pull data from the 2nd, 3rd and 5th columns.
   (Note: You can do all of these at the same time.)

In [145]:
clean1 = np.genfromtxt("/content/drive/MyDrive/Lending-Company-Total-Price.csv", delimiter=",",
                      dtype=str,
                      skip_header=1,
                      skip_footer=15,
                      usecols=(1,3,4),
                      )
print(clean1)

[['id_1' 'Male' 'Location 2']
 ['id_2' 'Male' 'Location 3']
 ['id_3' 'Female' 'Location 5']
 ...
 ['id_398' 'Male' 'Location 29']
 ['id_399' 'Male' 'Location 73']
 ['id_400' 'Male' 'Location 53']]


In [146]:
clean1, clean2,clean3 = np.genfromtxt("/content/drive/MyDrive/Lending-Company-Total-Price.csv", delimiter=",",
                      dtype=str,
                      skip_header=1,
                      skip_footer=15,
                      usecols=(1,3,4),
                      unpack=True)
print(pd.Series(clean1))
print(pd.Series(clean2))
print(pd.Series(clean3))

0        id_1
1        id_2
2        id_3
3        id_4
4        id_5
        ...  
395    id_396
396    id_397
397    id_398
398    id_399
399    id_400
Length: 400, dtype: object
0        Male
1        Male
2      Female
3        Male
4      Female
        ...  
395    Female
396      Male
397      Male
398      Male
399      Male
Length: 400, dtype: object
0        Location 2
1        Location 3
2        Location 5
3        Location 6
4        Location 7
           ...     
395    Location 195
396     Location 57
397     Location 29
398     Location 73
399     Location 53
Length: 400, dtype: object


### 5. Refer to the documentation of the np.genfromtxt() function and examine the following arguments and what they do:
    A) comments
    B) converters
    C) missing_values
    D) excludelist
    E) deletechars
    D) replace_space
    E) autostrip
   (You're <b>not</b> expected to provide any coding for this part. The cell below is provided for your convenience in case you want to try using the arguments as you go through them.)

In [147]:
url='/content/drive/MyDrive/Lending-Company-Total-Price.csv'
ad_clean = np.genfromtxt("/content/drive/MyDrive/Lending-Company-Total-Price.csv",
                         delimiter=',',
                         comments='#')
ad_clean

array([[   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [    1.,    nan,    nan, ...,    nan,    nan, 16600.],
       [    2.,    nan,    nan, ...,    nan,    nan, 16600.],
       ...,
       [  413.,    nan,    nan, ...,    nan,    nan, 16600.],
       [  414.,    nan,    nan, ...,    nan,    nan, 15600.],
       [  415.,    nan,    nan, ...,    nan,    nan, 22250.]])

In [148]:
# Tells NumPy that '???' means a missing number (NaN)
ad_clean = np.genfromtxt(url, delimiter=',', missing_values="???")
ad_clean

array([[   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [    1.,    nan,    nan, ...,    nan,    nan, 16600.],
       [    2.,    nan,    nan, ...,    nan,    nan, 16600.],
       ...,
       [  413.,    nan,    nan, ...,    nan,    nan, 16600.],
       [  414.,    nan,    nan, ...,    nan,    nan, 15600.],
       [  415.,    nan,    nan, ...,    nan,    nan, 22250.]])

In [149]:
# Removes '!' from names and ensures 'yield' isn't used as a variable name
ad_clean = np.genfromtxt(url, delimiter=',', names=True,
                         deletechars='!', excludelist=['yield'])
ad_clean

array([(  1., nan, nan, nan, nan, nan, 16600.), (  2., nan, nan, nan, nan, nan, 16600.), (  3., nan, nan, nan, nan, nan, 15600.),
       (  4., nan, nan, nan, nan, nan, 16600.), (  5., nan, nan, nan, nan, nan, 20250.), (  6., nan, nan, nan, nan, nan,    nan),
       (  7., nan, nan, nan, nan, nan, 20250.), (  8., nan, nan, nan, nan, nan, 16600.), (  9., nan, nan, nan, nan, nan, 22250.),
       ( 10., nan, nan, nan, nan, nan, 20250.), ( 11., nan, nan, nan, nan, nan, 16600.), ( 12., nan, nan, nan, nan, nan, 20250.),
       ( 13., nan, nan, nan, nan, nan, 16600.), ( 14., nan, nan, nan, nan, nan, 20750.), ( 15., nan, nan, nan, nan, nan, 22250.),
       ( 16., nan, nan, nan, nan, nan, 16600.), ( 17., nan, nan, nan, nan, nan, 22250.), ( 18., nan, nan, nan, nan, nan, 16600.),
       ( 19., nan, nan, nan, nan, nan, 16600.), ( 20., nan, nan, nan, nan, nan, 54625.), ( 21., nan, nan, nan, nan, nan, 16600.),
       ( 22., nan, nan, nan, nan, nan, 22250.), ( 23., nan, nan, nan, nan, nan, 19250.), (

In [150]:
# Turns "  5000  " into "5000" automatically
ad_clean = np.genfromtxt(url, delimiter=',', autostrip=True)
ad_clean

array([[   nan,    nan,    nan, ...,    nan,    nan,    nan],
       [    1.,    nan,    nan, ...,    nan,    nan, 16600.],
       [    2.,    nan,    nan, ...,    nan,    nan, 16600.],
       ...,
       [  413.,    nan,    nan, ...,    nan,    nan, 16600.],
       [  414.,    nan,    nan, ...,    nan,    nan, 15600.],
       [  415.,    nan,    nan, ...,    nan,    nan, 22250.]])

### 7. The first and last columns were the only ones with numeric data, so let's import only them.

In [151]:
fl=np.genfromtxt('/content/drive/MyDrive/Lending-Company-Total-Price.csv',
                 delimiter=',',
                 dtype=int,
                  usecols=(0, 6),      # Only 1st and last columns
                  missing_values='',   # Identify empty strings as missing
                  filling_values='0'   # Replace those blanks with 0
                  )
fl

array([[    0,     0],
       [    1, 16600],
       [    2, 16600],
       [    3, 15600],
       [    4, 16600],
       [    5, 20250],
       [    6,     0],
       [    7, 20250],
       [    8, 16600],
       [    9, 22250],
       [   10, 20250],
       [   11, 16600],
       [   12, 20250],
       [   13, 16600],
       [   14, 20750],
       [   15, 22250],
       [   16, 16600],
       [   17, 22250],
       [   18, 16600],
       [   19, 16600],
       [   20, 54625],
       [   21, 16600],
       [   22, 22250],
       [   23, 19250],
       [   24, 15600],
       [   25, 20250],
       [   26, 22250],
       [   27, 19250],
       [   28, 69225],
       [   29, 20250],
       [   30, 16600],
       [   31, 16600],
       [   32, 16600],
       [   33, 19250],
       [   34, 16600],
       [   35, 19250],
       [   36, 16600],
       [   37, 16600],
       [   38, 16600],
       [   39, 15600],
       [   40, 16600],
       [   41, 16600],
       [   42, 16600],
       [   

In [152]:
#type(fl)
print(fl[:,-1:]) # Displayin the last entrie row using slicing
print(fl[::,0]) # Displaying the first entire row using slicing

[[    0]
 [16600]
 [16600]
 [15600]
 [16600]
 [20250]
 [    0]
 [20250]
 [16600]
 [22250]
 [20250]
 [16600]
 [20250]
 [16600]
 [20750]
 [22250]
 [16600]
 [22250]
 [16600]
 [16600]
 [54625]
 [16600]
 [22250]
 [19250]
 [15600]
 [20250]
 [22250]
 [19250]
 [69225]
 [20250]
 [16600]
 [16600]
 [16600]
 [19250]
 [16600]
 [19250]
 [16600]
 [16600]
 [16600]
 [15600]
 [16600]
 [16600]
 [16600]
 [19250]
 [15600]
 [19250]
 [16600]
 [16600]
 [16600]
 [20250]
 [22250]
 [16600]
 [20250]
 [20250]
 [16600]
 [16600]
 [16600]
 [    0]
 [16600]
 [16600]
 [16600]
 [19250]
 [15600]
 [15600]
 [20250]
 [16600]
 [22250]
 [22250]
 [20250]
 [20250]
 [16600]
 [15600]
 [16600]
 [16600]
 [22250]
 [20750]
 [22250]
 [19250]
 [20250]
 [20250]
 [20250]
 [19250]
 [16600]
 [22250]
 [20250]
 [16600]
 [19250]
 [22250]
 [16600]
 [19250]
 [16600]
 [    0]
 [20250]
 [16600]
 [16600]
 [19250]
 [16600]
 [16600]
 [22250]
 [22250]
 [16600]
 [16600]
 [19250]
 [16600]
 [22250]
 [19250]
 [16600]
 [16600]
 [19250]
 [16600]
 [22250]
 