<a href="https://colab.research.google.com/github/krishnavarathan/python-data-analysis/blob/main/Numpy_Fundamentals_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
import numpy as np

Set the last column of array_2D to 100. Display the array to check your work.

Set all the values of array_3D to 1000. Display the array to check your work.

In [76]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

# #1. array_1D
# array_2D[-1]=100
# print( array_2D)


# #2. array_2D
# array_3D[-1,-1]=1000
# print( array_3D)a

#1. array_1D
array_2D[:,-1]=100
print( array_2D)


#2. array_2D
array_3D[:]=1000
print( array_3D)


[[ 20  30  40  50 100]
 [ 43  54  65  76 100]
 [ 11  22  33  44 100]]
[[[1000 1000 1000 1000 1000]
  [1000 1000 1000 1000 1000]]

 [[1000 1000 1000 1000 1000]
  [1000 1000 1000 1000 1000]]]


### Modifying Specific Elements of Arrays

This section demonstrates how to modify specific elements within 1D, 2D, and 3D NumPy arrays using negative indexing to access elements from the end of the array.

In [77]:
a=np.array([[[1,1,1,1,],[2,2,2,2],[3,3,3,3],[4,4,4,4]]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D[0,1,0]
array_1D = np.array([10,11,12,13,14])
array_1D[0]

np.int64(10)

### Sum of Array Elements

This section demonstrates how to calculate the sum of elements in the first row of a 2D NumPy array.

In [78]:
array_1D = np.array([10,11,12,13,14])
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

#1.
print(array_2D[0].sum())

200


### Modifying Arrays Using Slicing

This section demonstrates how to modify an entire column of a 2D NumPy array and all elements of a 3D NumPy array using slicing.

In [79]:
array_1D = np.array([10,11,12,13,14])
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
# print(array_1D)
# print(array_2D)
# print(array_3D)

# #1. array_1D
array_1D[-2] = 10
print(array_1D)
# #2. array_2D
array_2D[-1,-2] = 10
print(array_2D)
# #3. array_3D
array_3D[-1,-1,-2] = 10
print(array_3D)

[10 11 12 10 14]
[[20 30 40 50 60]
 [43 54 65 76 87]
 [11 22 33 10 55]]
[[[ 1  2  3  4  5]
  [11 21 31 41 51]]

 [[11 12 13 14 15]
  [51 52 53 10  5]]]


Consider the provided NumPy arrays to solve the following three exercises:

Display the sum of array_1D and the first row of array_2D.

Display the product of array_1D and the second row of array_2D.

Display the difference between the third row of array_2D and the second row of the second array in array_3D

In [80]:
array_1D = np.array([10,11,12,13,14])
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
# print(array_2D[2])
# print(array_3D[1,1])


#1.
print(array_1D+array_2D[0])

# #2.
print(array_1D*array_2D[1])

#3.
print(array_2D[2] - array_3D[1,1])

[30 41 52 63 74]
[ 430  594  780  988 1218]
[-40 -30 -20 -10  50]


Types of Data Supported by NumPy - Exercise #1
Before execution, add or modify the given code so that:

array_1D is composed of strings, and

array_2D is composed of 32-bit floats.

Use the same data values as in the original arrays.

In [81]:
array_1D = np.array([10,11,12,13,14], dtype=str)
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype='float32')

#1.
print(array_1D)
#2.
print(array_2D)

['10' '11' '12' '13' '14']
[[20. 30. 40. 50. 60.]
 [43. 54. 65. 76. 87.]
 [11. 22. 33. 44. 55.]]


**Typecasting**

In [82]:
x=np.array([[10,11,12,13,14], [10,11,12,13,14]])
y=np.array([10,11,12,13,14])
y=np.add(y, 4)
np.add(x,y, dtype=str)

array([['1014', '1115', '1216', '1317', '1418'],
       ['1014', '1115', '1216', '1317', '1418']], dtype='<U42')

**Axis**

In [83]:
print(x)
print(np.mean(x, axis=0)) # column-wise mean calculated
print(np.mean(x, axis=1)) # row-wise mean calculated

[[10 11 12 13 14]
 [10 11 12 13 14]]
[10. 11. 12. 13. 14.]
[12. 12.]


In [84]:
a=[10, 11, 11, 11 ,12]
b=x[1]
print(b)
np.mean(a)

[10 11 12 13 14]


np.float64(11.0)

Characteristics of NumPy Functions - Exercise #2
1. Before execution, add or modify the given code so that
array_2D and array_3D are composed of 32-bit float values.

2. Use the axis argument of the np.mean() function to compute the mean for every column of the 2-dimensional array array_2D.

3. Use the axis argument of the np.mean() function to compute the mean for each two-dimensional sub-array in the three-dimensional array array_3D, along its rows
(i.e., compute the column-wise mean within each sub-array).

Display the results for 2. and 3.


In [85]:
#1.
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype='float32')
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]], dtype='float32')


#2.
print(np.mean(array_2D, axis=0))
#3.
print(np.mean(array_3D, axis=1))

[24.666666 35.333332 46.       56.666668 67.333336]
[[ 6.  11.5 17.  22.5 28. ]
 [31.  32.  33.  34.  10. ]]
