<a href="https://colab.research.google.com/github/krishnavarathan/python-data-analysis/blob/main/NumPy_DataTypes_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy DataTypes

In [180]:
import numpy as np

### 1. With the help of the <i> np.array() </i>function, create a 1-D array variable <i> array_hw_1 </i> with the numbers from 1 to 8 and display it on the screen.

In [181]:
array_hw_1 = np.array(range(1,9))
array_hw_1

array([1, 2, 3, 4, 5, 6, 7, 8])

### 2.Check its type, shape and size.
<i> (<b>Hint </b>: "type" is a Python function, while "shape" and "size" are attributes of the array) </i>

In [182]:
# It will return the dimensions of the np.array
array_hw_1.ndim

1

In [183]:
type(array_hw_1)

numpy.ndarray

In [184]:
array_hw_1.shape

(8,)

In [185]:
array_hw_1.size

8

### 3. Now, create a 2x4 2-D array, <i> array_hw_2</i> with the same values & display it on screen.

In [186]:
array_hw_2 = np.array([list(array_hw_1), list(array_hw_1)])
array_hw_2

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

### 4. Find its type, shape, and size.

In [187]:
# It will return the dimensions of the np.array
array_hw_2.ndim

2

In [188]:
array_hw_2.shape

(2, 8)

In [189]:
array_hw_2.size

16

In [190]:
type(array_hw_2)

numpy.ndarray

### 5. Use square brackets to create a 3-D array with the same values as <i> array_hw_2 </i> and display it on screen.

In [191]:
array_hw_3=np.array([[list(array_hw_1), list(array_hw_1)], [list(array_hw_1), list(array_hw_1)], [list(array_hw_1), list(array_hw_1)], [list(array_hw_1), list(array_hw_1)]])
array_hw_3

array([[[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]],

       [[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]],

       [[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]],

       [[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]]])

### 6. Find its type, shape and size.


In [192]:
# It will return the dimensions of the np.array
array_hw_3.ndim

3

In [193]:
array_hw_3.shape

(4, 2, 8)

In [194]:
array_hw_3.size

64

In [195]:
type(array_hw_3)

numpy.ndarray

### 7. Define a 2-D list <i> list_hw_1 </i> with the same values as <i> array_hw_2 </i>and display it on screen.

In [196]:
list_hw_1 = [[1,2,3,4],[5,6,7,8]]
list_hw_1

[[1, 2, 3, 4], [5, 6, 7, 8]]

### 8. Find the length of this 2-D list.

In [197]:
len(list_hw_1)

2

### 9. Fint the length of one of its sublists.

In [198]:
print(len(list_hw_1[0]))
print(len(list_hw_1[1]))

4
4


### 10. Verify its type.

In [199]:
print(type(list_hw_1[0]))

<class 'list'>


### 11. Use the <i>np.array()</i> function to create an array out of <i> list_hw_1</i> and display it on screen.

In [200]:
array_hw_4 = np.array(list_hw_1)

In [201]:
array_hw_4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 12. Create two more variables and display them on screen:
    A) A list which is the sum of the two sublists of list_hw_1;
    B) An array which is the sum of the two subarrays of array_hw_4;
    
    (Hint: Use indexing to refer to the different sub-lists/arrays)

In [202]:
list_sum=list_hw_1[0] + list_hw_1[1]

In [203]:
array_sum= array_hw_4[0] + array_hw_4[1]

In [204]:
list_sum

[1, 2, 3, 4, 5, 6, 7, 8]

In [205]:
array_sum

array([ 6,  8, 10, 12])

### 13. Find the square roots of all the elements in <i> array_sum </i>
   <i> (<b>Hint</b>: Use the np.sqrt() function)

In [206]:
np.sqrt(array_sum)

array([2.44948974, 2.82842712, 3.16227766, 3.46410162])

### 13. Find the square roots of all the elements in <i> list_sum </i>
   <i> (<b>Hint</b>: Most NumPy functions are equipped to handle <b> lists </b>like ndarrays with the same shape)

In [207]:
np.sqrt(list_sum)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712])

### 14. Use <i> np.genfromtxt() </i> to import the <i> "Lending-Company-Total-Price.csv" </i> file as strings and display its contents.
    You can open the file in a text editor like Notepad++ to check its delimiter.

In [208]:
data=np.genfromtxt('/content/drive/MyDrive/Lending-Company-Total-Price.csv',
                   delimiter=',',
                   dtype=str)

In [209]:
data

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2', '16600'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600'],
       ...,
       ['413', 'id_413', 'Product B', ..., 'Location 135', 'Region 1',
        '16600'],
       ['414', 'id_414', 'Product C', ..., 'Location 200', 'Region 6',
        '15600'],
       ['415', 'id_415', 'Product A', ..., 'Location 8', 'Region 2',
        '22250']], dtype='<U14')

### 15. Use the <i> skip_header </i> and <i> usecols </i> parameters to only take the numerical data from the file. Then, let's see how the inputs change if we alter the datatype argument to:

    A) The default (not specify it)
    B) 32-bit integers (np.int32)
    C) 32-bit floats (np.float32)
    D) 64-bit complex numbers (np.complex64)
    E) Unicode (np.unicode)
    F) Objects (np.object)
    G) None

In [210]:
data_2=np.genfromtxt('/content/drive/MyDrive/Lending-Company-Total-Price.csv',
                   delimiter=',',
                    # dtype = np.int32,     # B)
                    # dtype = np.float32,   # C)
                    # dtype = np.complex64, # D)
                    # dtype = np.unicode,   # E)
                    # dtype = np.objects,   # F)
                    # dype = None           # G)
                   dtype=int,
                   skip_header=1,
                   usecols=(0,-1))
data_2

array([[    1, 16600],
       [    2, 16600],
       [    3, 15600],
       [    4, 16600],
       [    5, 20250],
       [    6,    -1],
       [    7, 20250],
       [    8, 16600],
       [    9, 22250],
       [   10, 20250],
       [   11, 16600],
       [   12, 20250],
       [   13, 16600],
       [   14, 20750],
       [   15, 22250],
       [   16, 16600],
       [   17, 22250],
       [   18, 16600],
       [   19, 16600],
       [   20, 54625],
       [   21, 16600],
       [   22, 22250],
       [   23, 19250],
       [   24, 15600],
       [   25, 20250],
       [   26, 22250],
       [   27, 19250],
       [   28, 69225],
       [   29, 20250],
       [   30, 16600],
       [   31, 16600],
       [   32, 16600],
       [   33, 19250],
       [   34, 16600],
       [   35, 19250],
       [   36, 16600],
       [   37, 16600],
       [   38, 16600],
       [   39, 15600],
       [   40, 16600],
       [   41, 16600],
       [   42, 16600],
       [   43, 19250],
       [   

### 16. Setting the datatype to None means the function automatically chooses the datatype for each column of the text file, so let's see how this works for all the columns.

In [211]:
data_none=np.genfromtxt('/content/drive/MyDrive/Lending-Company-Total-Price.csv',
                   delimiter=',',
                   dtype=None)
data_none

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2', '16600'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600'],
       ...,
       ['413', 'id_413', 'Product B', ..., 'Location 135', 'Region 1',
        '16600'],
       ['414', 'id_414', 'Product C', ..., 'Location 200', 'Region 6',
        '15600'],
       ['415', 'id_415', 'Product A', ..., 'Location 8', 'Region 2',
        '22250']], dtype='<U14')