<a href="https://colab.research.google.com/github/krishnavarathan/python-data-analysis/blob/main/Pandas_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<hr style="border:5px solid #108999"> </hr>

In [120]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# pandas Series <hr style="border:4.5px solid #108999"> </hr>

## pandas Series: .unique() & .nunique()

In [121]:
import pandas as pd

In [122]:
data = pd.read_csv('/content/drive/MyDrive/Pandas_Exercises/Location.csv')
location_data = data.copy()
location_data.head()

Location
0   Location 3
1   Location 6
2   Location 8
3  Location 26
4  Location 34

In [123]:
type(location_data)

pandas.core.frame.DataFrame

In [124]:
location_data.describe()

Location
count          1043
unique          296
top     Location 25
freq             31

In [125]:
len(location_data)

1043

In [126]:
location_data.nunique()

Location    296
dtype: int64

In [127]:
type(location_data)

pandas.core.frame.DataFrame

In [128]:
location_data["Location"].unique()

array(['Location 3', 'Location 6', 'Location 8', 'Location 26',
       'Location 34', 'Location 25', 'Location 46', 'Location 156',
       'Location 21', 'Location 13', 'Location 579', 'Location 602',
       'Location 10', 'Location 44', 'Location 30', 'Location 48',
       'Location 196', 'Location 64', 'Location 91', 'Location 62',
       'Location 75', 'Location 42', 'Location 233', 'Location 95',
       'Location 78', 'Location 61', 'Location 87', 'Location 19',
       'Location 115', 'Location 350', 'Location 377', 'Location 17',
       'Location 113', 'Location 81', 'Location 58', 'Location 212',
       'Location 53', 'Location 337', 'Location 41', 'Location 632',
       'Location 73', 'Location 214', 'Location 218', 'Location 38',
       'Location 172', 'Location 197', 'Location 101', 'Location 185',
       'Location 129', 'Location 235', 'Location 142', 'Location 50',
       'Location 76', 'Location 11', 'Location 33', 'Location 22',
       'Location 145', 'Location 203', 'Loca

In [129]:
type(location_data['Location'].unique())

numpy.ndarray

In [130]:
location_data['Location'].unique()

array(['Location 3', 'Location 6', 'Location 8', 'Location 26',
       'Location 34', 'Location 25', 'Location 46', 'Location 156',
       'Location 21', 'Location 13', 'Location 579', 'Location 602',
       'Location 10', 'Location 44', 'Location 30', 'Location 48',
       'Location 196', 'Location 64', 'Location 91', 'Location 62',
       'Location 75', 'Location 42', 'Location 233', 'Location 95',
       'Location 78', 'Location 61', 'Location 87', 'Location 19',
       'Location 115', 'Location 350', 'Location 377', 'Location 17',
       'Location 113', 'Location 81', 'Location 58', 'Location 212',
       'Location 53', 'Location 337', 'Location 41', 'Location 632',
       'Location 73', 'Location 214', 'Location 218', 'Location 38',
       'Location 172', 'Location 197', 'Location 101', 'Location 185',
       'Location 129', 'Location 235', 'Location 142', 'Location 50',
       'Location 76', 'Location 11', 'Location 33', 'Location 22',
       'Location 145', 'Location 203', 'Loca

In [131]:
type(location_data['Location'].unique)

method

## pandas Series: Converting Series into Arrays (.values, .array, .to_numpy())

In [132]:
import pandas as pd
import numpy as np

In [133]:
prices_per_category = pd.Series({'Product A': 22250, 'Product B' : 16600, 'Product C':15600, 'Product D':[9089,8765]})
prices_per_category

Product A           22250
Product B           16600
Product C           15600
Product D    [9089, 8765]
dtype: object

In [134]:
prices_per_category.values

array([22250, 16600, 15600, list([9089, 8765])], dtype=object)

In [135]:
type(prices_per_category.values)

numpy.ndarray

In [136]:
prices_per_category.array

<NumpyExtensionArray>
[22250, 16600, 15600, [9089, 8765]]
Length: 4, dtype: object

In [137]:
print(type(prices_per_category.array))

<class 'pandas.core.arrays.numpy_.NumpyExtensionArray'>


In [138]:
prices_per_category.to_numpy()

array([22250, 16600, 15600, list([9089, 8765])], dtype=object)

In [139]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [140]:
test_array = prices_per_category[['Product A', 'Product B', 'Product C']].to_numpy(dtype='float')
test_array

array([22250., 16600., 15600.])

In [141]:
type(test_array[0])

numpy.float64

In [142]:
prices_per_category.values[0]

22250

In [143]:
type(prices_per_category.values[0])

int

In [144]:
prices_per_category.array[0]

22250

In [145]:
type(prices_per_category.array[0])


int

In [146]:
prices_per_category.to_numpy()[0]

22250

In [147]:
type(prices_per_category.to_numpy()[0])

int

## pandas Series: .sort_values()

In [148]:
import pandas as pd

In [149]:
numbers = pd.Series([15, 1000, 23, 45, 444])
numbers

0      15
1    1000
2      23
3      45
4     444
dtype: int64

In [150]:
numbers.sort_values()

0      15
2      23
3      45
4     444
1    1000
dtype: int64

In [151]:
numbers.sort_values(ascending=True)

0      15
2      23
3      45
4     444
1    1000
dtype: int64

In [152]:
numbers.sort_values(ascending=False)

1    1000
4     444
3      45
2      23
0      15
dtype: int64

In [153]:
data = pd.read_csv('/content/drive/MyDrive/Pandas_Exercises/Location.csv')
location_data = data.copy()
location_data.head()

Location
0   Location 3
1   Location 6
2   Location 8
3  Location 26
4  Location 34

In [154]:
location_data.sort_values(by="Location")

Location
637   Location 1
884   Location 1
465   Location 1
716  Location 10
623  Location 10
..           ...
482  Location 97
128  Location 97
669  Location 97
757  Location 98
372  Location 99

[1043 rows x 1 columns]

In [155]:
location_data.sort_values(by="Location", ascending=True)

Location
637   Location 1
884   Location 1
465   Location 1
716  Location 10
623  Location 10
..           ...
482  Location 97
128  Location 97
669  Location 97
757  Location 98
372  Location 99

[1043 rows x 1 columns]

In [156]:
location_data.sort_values(by="Location", ascending=False)

Location
372  Location 99
757  Location 98
128  Location 97
482  Location 97
271  Location 97
..           ...
202  Location 10
298  Location 10
637   Location 1
884   Location 1
465   Location 1

[1043 rows x 1 columns]

## Attribute and Method Chaining

In [157]:
import pandas as pd

In [158]:
data = pd.read_csv('/content/drive/MyDrive/Pandas_Exercises/Location.csv')
location_data = data.copy()
location_data.head()
location_data.tail()

Location
1038  Location 73
1039  Location 82
1040  Location 11
1041  Location 26
1042  Location 94

In [159]:
location_data.index

RangeIndex(start=0, stop=1043, step=1)

In [160]:
location_data.values

array([['Location 3'],
       ['Location 6'],
       ['Location 8'],
       ...,
       ['Location 11'],
       ['Location 26'],
       ['Location 94']], dtype=object)

In [161]:
print(location_data.index.name)

None


In [162]:
location_data.index.name = 'Index'

In [163]:
location_data

Location
Index             
0       Location 3
1       Location 6
2       Location 8
3      Location 26
4      Location 34
...            ...
1038   Location 73
1039   Location 82
1040   Location 11
1041   Location 26
1042   Location 94

[1043 rows x 1 columns]

In [164]:
location_data.index.name

'Index'

In [165]:
location_data.sort_values(by='Location')

Location
Index             
637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
...            ...
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99

[1043 rows x 1 columns]

In [166]:
location_data.sort_values(by='Location').head()

Location
Index             
637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10

In [167]:
location_data.sort_values(by='Location').tail()

Location
Index             
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99

In [168]:
location_data.index

RangeIndex(start=0, stop=1043, step=1, name='Index')

In [169]:
type(location_data.index)

pandas.core.indexes.range.RangeIndex

In [170]:
location_data.index.to_numpy()

array([   0,    1,    2, ..., 1040, 1041, 1042])

## pandas Series: .sort_index()

In [171]:
import pandas as pd

In [172]:
data = pd.read_csv('/content/drive/MyDrive/Pandas_Exercises/Location.csv')
location_data = data.copy()
location_data.head()

Location
0   Location 3
1   Location 6
2   Location 8
3  Location 26
4  Location 34

In [173]:
location_data.sort_values(by='Location', ascending=False)

Location
372  Location 99
757  Location 98
128  Location 97
482  Location 97
271  Location 97
..           ...
202  Location 10
298  Location 10
637   Location 1
884   Location 1
465   Location 1

[1043 rows x 1 columns]

In [174]:
location_data_sv = location_data.sort_values(by='Location', ascending=False)
location_data_sv.head()

Location
372  Location 99
757  Location 98
128  Location 97
482  Location 97
271  Location 97

In [175]:
location_data_sv.index

Index([ 372,  757,  128,  482,  271,  669,  612,   29,  518,  598,
       ...
        904,  912, 1010,   14,  716,  202,  298,  637,  884,  465],
      dtype='int64', length=1043)

In [176]:
location_data_sv.index.sort_values()

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042],
      dtype='int64', length=1043)

In [177]:
location_data_sv.head()

Location
372  Location 99
757  Location 98
128  Location 97
482  Location 97
271  Location 97

In [178]:
location_data_sv.index = location_data_sv.index.sort_values()

In [179]:
location_data_sv

Location
0     Location 99
1     Location 98
2     Location 97
3     Location 97
4     Location 97
...           ...
1038  Location 10
1039  Location 10
1040   Location 1
1041   Location 1
1042   Location 1

[1043 rows x 1 columns]

In [180]:
location_data_sv = location_data.sort_values(by='Location', ascending=False)
location_data_sv.head()

Location
372  Location 99
757  Location 98
128  Location 97
482  Location 97
271  Location 97

In [181]:
location_data_sv.sort_index()

Location
0      Location 3
1      Location 6
2      Location 8
3     Location 26
4     Location 34
...           ...
1038  Location 73
1039  Location 82
1040  Location 11
1041  Location 26
1042  Location 94

[1043 rows x 1 columns]

In [182]:
location_data_sv

Location
372  Location 99
757  Location 98
128  Location 97
482  Location 97
271  Location 97
..           ...
202  Location 10
298  Location 10
637   Location 1
884   Location 1
465   Location 1

[1043 rows x 1 columns]

In [183]:
location_data_sv = location_data_sv.sort_index(ascending=True)
location_data_sv

Location
0      Location 3
1      Location 6
2      Location 8
3     Location 26
4     Location 34
...           ...
1038  Location 73
1039  Location 82
1040  Location 11
1041  Location 26
1042  Location 94

[1043 rows x 1 columns]