<a href="https://colab.research.google.com/github/krishnavarathan/python-data-analysis/blob/main/Slicing_in_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

**Slicing in NumPy - Exercise #1**&
Consider the provided 2D array and supply arguments to the print() functions to complete the following tasks:

1. Slice the first column of the 2D array.

2. Slice the last column of the 2D array.

3. Slice the second row of the 2D array.

4. Slice the last two columns of the second row of the 2D array.

5. Slice the second row of the 2D array excluding the last two columns

6. Slice everything except the first row and last column of the 2D array.

7. Slice the 1st, 3rd and 5th columns of the 2D array.

In [8]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype = np.float32)

#1.
print(array_2D[:,0])
#2.
print(array_2D[:,-1])
#3.
print(array_2D[1,:])
#4.
print(array_2D[1,-2:])
#5.
print(array_2D[1,:-2])
#6.
print(array_2D[1:,:-1])
#7.
print(array_2D[:,0::2])

[20. 43. 11.]
[60. 87. 55.]
[43. 54. 65. 76. 87.]
[76. 87.]
[43. 54. 65.]
[[43. 54. 65. 76.]
 [11. 22. 33. 44.]]
[[20. 40. 60.]
 [43. 65. 87.]
 [11. 33. 55.]]


In [9]:
print(array_2D)

[[20. 30. 40. 50. 60.]
 [43. 54. 65. 76. 87.]
 [11. 22. 33. 44. 55.]]


**Slicing in NumPy - Exercise #2**
Consider the provided 3D array and supply arguments to the print() functions to complete the following tasks:

1. Slice the first column of both matrices in the 3D array.

2. Slice every other column of both matrices in the 3D array.

In [10]:

array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

#1.
print(array_3D[:,:,0])
#2.
print(array_3D[:,:,::2])

[[ 1 11]
 [11 51]]
[[[ 1  3  5]
  [11 31 51]]

 [[11 13 15]
  [51 53  5]]]


**Slicing in NumPy - Exercise #3**
Consider the provided arrays and complete the following tasks:

1. Use a conditional expression on array_1D as the argument to the given print() function to check which elements are greater than 10.

2. Use a conditional expression on array_2D as the argument to the given print() function to check which elements are greater than 10.

3. Use a conditional expression on array_3D as the argument to the given print() function to check which elements are greater than 10

In [11]:
array_1D = np.array([10,11,12,13,14])
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

#1.
print(array_1D>10)
#2.
print(array_2D>10)
#3.
print(array_3D>10)

[False  True  True  True  True]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[[False False False False False]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True False]]]


**Slicing in NumPy - Exercise #4**
Consider the provided arrays and complete the following tasks:

1. Use conditional slicing on array_1D as the argument to the given print() function to extract the elements greater than 10.

2. Use conditional slicing on array_2D as the argument to the given print() function to extract the elements greater than 10.

3. Use conditional slicing on array_3D as the argument to the given print() function to extract the elements greater than 10.

In [13]:
#1.
print(array_1D[array_1D>10])
#2.
print(array_2D[array_2D>10])
#3.
print(array_3D[array_3D>10])

[11 12 13 14]
[20 30 40 50 60 43 54 65 76 87 11 22 33 44 55]
[11 21 31 41 51 11 12 13 14 15 51 52 53 54]


**Slicing in NumPy - Exercise #5**
Consider the provided arrays and complete the following tasks:

1. Use conditional slicing on array_1D as the argument to the given print() function to extract the odd values greater than 10.

2. Use conditional slicing on array_2D as the argument to the given print() function to extract the odd values greater than 10.

3. Use conditional slicing on array_3D as the argument to the given print() function to extract the odd values greater than 10.

In [ ]:
#1
print(array_1D[((array_1D > 10) & (array_1D % 2 == 1))])
#2.
print(array_2D[((array_2D > 10) & (array_2D % 2 == 1))])
#3.
print(array_3D[((array_3D > 10) & (array_3D % 2 == 1))])

**Slicing in NumPy - Exercise #6**
Consider the provided arrays and complete the following tasks:

1. Use conditional slicing on array_1D as the argument to the given print() function to extract the values that are either odd, greater than 10, or both.

2. Use conditional slicing on array_2D as the argument to the given print() function to extract the values that are either odd, greater than 10, or both.

3. Use conditional slicing on array_3D as the argument to the given print() function to extract the values that are either odd, greater than 10, or both.

In [14]:
#1.
print(array_1D[((array_1D > 10) | (array_1D % 2 == 1))])
#2.
print(array_2D[((array_2D > 10) | (array_2D % 2 == 1))])
#3.
print(array_3D[((array_3D > 10) | (array_3D % 2 == 1))])

[11 12 13 14]
[20 30 40 50 60 43 54 65 76 87 11 22 33 44 55]
[ 1  3  5 11 21 31 41 51 11 12 13 14 15 51 52 53 54  5]


**Dimensions and the Squeeze Function - Exercise #1**
Use conditional slicing and indexing to access the first row of the first 2D array inside array_3D, and examine the shape of the resulting selections:

1.A

Access the first row of the first 2D array in array_3D using exact indices for both dimensions.

1.B

Check the shape of the resulting object.

2.A

Access the first row of the first 2D array in array_3D using a slice for the first dimension and an exact index for the second dimension.

2.B

Check the shape of the resulting object.

3.A

Access the first row of the first 2D array in array_3D using slices for both dimensions (from the start up to index 1).

3.B

Check the shape of the obtained object.

In [15]:
#1.A
print(array_3D[0, 0])
#1.B
print(array_3D[0, 0].shape)

#2.A
print(array_3D[:1, 0])
#2.B
print(array_3D[:1, 0].shape)

#3.A
print(array_3D[:1, :1])
#3.B
print(array_3D[:1, :1].shape)

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]]
(1, 5)
[[[1 2 3 4 5]]]
(1, 1, 5)


**Dimensions and the Squeeze Function - Exercise #2**
1. Since array_3D[:1,0] may include one or more redundant dimensions, use the squeeze() function to reduce them.

2. Check the shape of the resulting array.

In [16]:
print(np.squeeze(array_3D[:1,0]))
#2.
print(np.squeeze(array_3D[:1,0]).shape)

[1 2 3 4 5]
(5,)
